[package]
name = "csvs_convert"
version = "0.7.4"
edition = "2021"

description = "Some Datapackage Conversion"
license = "MIT"
repository = "https://github.com/kindly/csvs_convert"
homepage = "https://github.com/kindly/csvs_convert"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

chrono = { version = "0.4.19", default-features = false }
parquet = { version = "19.0.0", default-features = false, features = ["arrow", "snap"] }
arrow = { version = "19.0.0", default-features = false, features = ["csv"] }
serde_json = { version = "1.0.83", features = ["preserve_order"] }
csv = "1.1.6"
snafu = "0.7.1"
zip = { version = "0.6.2", default-features = false, features = ["deflate"] }
tempfile = "3.3.0"
walkdir = "2.3.2"
pathdiff = "0.2.1"
petgraph = { version = "0.6.2", default-features = false, features= ["graphmap"] }
rusqlite = { version = "0.28.0", features = ["bundled"] }
minijinja = { version = "0.26.0" }
typed-builder = "0.10.0"
xlsxwriter = "0.3.5"
lazy_static = "1.4.0"
regex = {version = "1.6.0", default-features = false}
postgres = "0.19.3"
tempdir = "0.3.7"
thiserror = "1.0.35"
pdatastructs = { version = "0.7.0", features = ["rand", "bytecount", "num-traits", "fixedbitset"], default-features = false }
streaming-stats = "0.2.3"
counter = "0.5.7"
crossbeam-channel = "0.5.6"
csv-index = "0.1.6"
threadpool = "1.8.1"

[profile.bench]
debug = true

[dev-dependencies]
assert-json-diff = "2.0.2"
insta = { version = "1.17.1", features = ["redactions"] }
