[package]
name = "csvs_convert"
version = "0.7.0"
edition = "2021"

description = "Some Datapackage Conversion"
license = "MIT"
repository = "https://github.com/kindly/csvs_convert"
homepage = "https://github.com/kindly/csvs_convert"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

chrono = "0.4.19"
parquet = { version = "19.0.0", default-features = false, features = ["arrow", "snap", "brotli", "flate2", "lz4", "base64"] }
arrow = "19.0.0"
serde_json = { version = "1.0.83", features = ["preserve_order"] }
csv = "1.1.6"
csv-sniffer = "0.3.1"
snafu = "0.7.1"
zip = "0.6.2"
tempfile = "3.3.0"
walkdir = "2.3.2"
pathdiff = "0.2.1"
petgraph = "0.6.2"
rusqlite = { version = "0.28.0", features = ["bundled"] }
minijinja = "0.26.0"
typed-builder = "0.10.0"
xlsxwriter = "0.3.5"
lazy_static = "1.4.0"
regex = "1.6.0"
postgres = "0.19.3"
tempdir = "0.3.7"
thiserror = "1.0.35"
pdatastructs = "0.7.0"
streaming-stats = "0.2.3"
counter = "0.5.7"

[dev-dependencies]
insta = { version = "1.17.1", features = ["redactions"] }
