[package]
name = "csvs_convert"
version = "0.7.9"
edition = "2021"

description = "Some Datapackage Conversion"
license = "MIT"
repository = "https://github.com/kindly/csvs_convert"
homepage = "https://github.com/kindly/csvs_convert"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

chrono = { version = "0.4.23", default-features = false }
serde_json = { version = "1.0.91", features = ["preserve_order"] }
csv = "1.1.6"
snafu = "0.7.3"
tempfile = "3.3.0"
walkdir = "2.3.2"
pathdiff = "0.2.1"
petgraph = { version = "0.6.2", default-features = false, features= ["graphmap"] }
typed-builder = "0.11.0"
lazy_static = "1.4.0"
regex = {version = "1.7.0", default-features = false}
thiserror = "1.0.38"
pdatastructs = { version = "0.7.0", features = ["rand", "bytecount", "num-traits", "fixedbitset"], default-features = false }
streaming-stats = "0.2.3"
counter = "0.5.7"
crossbeam-channel = "0.5.6"
csv-index = "0.1.6"
threadpool = "1.8.1"

[target.'cfg(not(target_family = "wasm"))'.dependencies]

parquet = { version = "29.0.0", default-features = false, features = ["arrow", "snap"] }
arrow = { version = "29.0.0", default-features = false, features = ["csv"] }
xlsxwriter = "0.5.0"
postgres = "0.19.4"
minijinja = { version = "0.27.0" }
zip = { version = "0.6.3", default-features = false, features = ["deflate"] }
rusqlite = { version = "0.28.0", features = ["bundled"] }

[target.'cfg(target_family = "wasm")'.dependencies]
getrandom = {version="0.2", features = ["js"]}
regex = {version="1.7", features = ["std"]}

[profile.bench]
debug = true

[dev-dependencies]
assert-json-diff = "2.0.2"
insta = { version = "1.23.0", features = ["redactions", "yaml"] }
