[package]
name = "datapackage_convert"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

parquet = "10.0.0"
arrow = "10.0.0"
serde_json = { version = "1.0.79", features = ["preserve_order"] }
csv = "1.1.6"
snafu = "0.7.0"
zip = "0.6.0"
tempfile = "3.3.0"
walkdir = "2.3.2"

[dev-dependencies]
insta = { version = "1.14.0", features = ["redactions"] }
