[package]
name = "datapackage_convert"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

parquet = "9.1.0"
arrow = "9.1.0"
serde_json = { version = "1", features = ["preserve_order"] }
csv = "1"
snafu = {version = "0.7.0"}
zip = "0.6"

[dev-dependencies]
insta = {version = "1.12.0", features = ["redactions"]}
